const permissions = {
  MA: [
    '/user/search',
    '/appointment/search',
    '/appointment/[appointmentId]',
    '/appointment/ongoing',
    '/appointment/canceled',
    '/appointment/history',
    '/appointment/refunded',
    '/user/list',
    '/user/[userId]',
    '/doctor/list',
    '/doctor/[doctor]',
  ],
  PRO: [
    '/user/search',
    '/appointment/search',
    '/appointment/[appointmentId]',
    '/appointment/ongoing',
    '/appointment/canceled',
    '/appointment/history',
    '/appointment/refunded',
    '/meet-specialist',
    '/manual/create-appointment',
    '/manual/create-case',
  ],
  FINANCE: [
    '/user/search',
    '/appointment/search',
    '/appointment/[appointmentId]',
    '/appointment/ongoing',
    '/appointment/canceled',
    '/appointment/history',
    '/appointment/refunded',
    '/confirm-payment',
    '/invoice/setting',
    '/payment/voucher-transaction-v2/list',
  ],
  MARKETING: [
    '/user/search',
    '/promotion',
    '/promotion/add',
    '/promotion/edit/[id]',
    '/promotion/detail/[id]',
    '/appointment/search',
    '/appointment/[appointmentId]',
    '/payment/data-voucher/list',
    '/payment/data-voucher/add',
    '/payment/data-voucher/detail/[id]',
    '/payment/data-voucher/edit/[id]',
    '/payment/voucher-transaction/list',
    '/payment/voucher-transaction-v2/list',
  ],
  CUSTOMER_SERVICE: [
    '/user/search',
    '/appointment/search',
    '/appointment/[appointmentId]',
    '/user/[userId]',
  ],
}

export default permissions
